### ISSUE TITLE
Issue Design: Sound Submit Prompt

### ISSUE THREAD

**Issue by jiraslama** [alan-turing-institute/AutisticaCitizenScience#289] opened 2020-06-23 22:34 UTC
Priority: Low Priority

As a: Designer, I would like to create for the community a wireframe design for the experience page which adds a sound prompt (effect) on the experience page - submit button. Which will alert the user that a experience has been successfully submitted.
So that the community can provide feedback on the wireframe design, which can be taken into the prototype design stage on the project board as a concept to ensure the platform is being developed in the correct way

Acceptance criteria:
Review issue designs, research and wireframes take on board area as required.
Define how this user story will close

Notes:
Associated pull request: Sprint 5 MVP Structure (File Management Demo)
Components to design - wireframe and then share with developers

Current status: Considerations Design - Design Research Notes
Wireframes Interactive & Dev Reference Screens

**Comment by GeorgiaHCA** [comment] 2020-07-08 05:44
Heya @jiraslama - I notice that this looks like a potential duplicate of issue #296? Let me know if the newer issue has replaced this one and if so I can close it. Thanks.

**Comment by jiraslama** [comment] 2020-07-20 13:29
Hi Georgia, Yes this is a duplication of 296 please delete this one. Thanks Chris

**Closed** 2020-07-20 13:43 UTC
Labels: duplicate
